app.title=Jettra Flux Plugin Center
app.shorttitle=FS
server.port=9010
server.contextpath=/jettrafluxplugincenter
#server.contextpath=/facliserver
server.compactheader=true
server.session.timeout=0
app.language=es
#app.theme=3d
app.theme=sai
app.animated=false
server.hotreload=true
baseUri=http://localhost:9010/facliserver
server.typebackend=true
#JWT Security
server.JWT_SECRET = default_secret_key_jettra_rest_2026
server.JWT_EXPIRATION=3600000
server.consoleshowregisterpage=false

