package jcf;

/**
 * Auto-generated by JettraEE from jettra-config.properties.
 */
public enum AppRole {
    ADMINISTRADOR,
    GERENTE,
    ANONIMO;

    public String getValue() {
        return name();
    }
}
